---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-db
  namespace: couchbase
  labels:
    app: couchbase
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 8091
    targetPort: http
  - name: https
    port: 18091
    targetPort: https
  selector:
    app: couchbase